feat: Add safe prompt messages logging for debug
Characters such as `<>` are interepreted by loguru as markup tags.  When
logging such tags with unexpected content, for instance, an email
address `<notifications@github.com>`, an error will be raised:
```
ValueError: Tag "<notifications@github.com>" does not correspond to any
known color directive, make sure you did not misspelled it (or prepend
'\' to escape it)
```

To avoid this, an escaping function is added to remove such tags.

See https://loguru.readthedocs.io/en/stable/api/logger.html#color